# Usage:
#   podman kube play cloud-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: cloud-pod
spec:
  containers:
    # -----------------------------------------------------
    # PostgreSQL (pgvector)
    # -----------------------------------------------------
    - name: postgres
      image: docker.io/pgvector/pgvector:pg17
      env:
        - name: POSTGRES_USER
          value: "postgres_user"
        - name: POSTGRES_PASSWORD
          value: "postgres_p@ssword"
        - name: PGDATA
          value: /var/lib/postgresql/data
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-initdb
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      restartPolicy: Always

    # -----------------------------------------------------
    # Redis
    # -----------------------------------------------------
    - name: redis
      image: docker.io/library/redis:latest
      args: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-data
          mountPath: /data
      restartPolicy: Always

    # -----------------------------------------------------
    # Immich Server
    # -----------------------------------------------------
    - name: immich-server
      image: ghcr.io/immich-app/immich-server:release
      env:
        - name: DB_HOSTNAME
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "immich_user"
        - name: DB_PASSWORD
          value: "immich_db_p@ssword"
        - name: DB_DATABASE_NAME
          value: "immich_db"
        - name: REDIS_HOSTNAME
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: IMMICH_MEDIA_LOCATION
          value: "/usr/src/app/upload"
      ports:
        - containerPort: 2283
          hostPort: 2283
      volumeMounts:
        - name: immich-uploads
          mountPath: /usr/src/app/upload
        - name: immich-thumbs
          mountPath: /usr/src/app/thumbs
        - name: photo-archive
          mountPath: /mnt/photo_archive
          readOnly: true
      restartPolicy: Always

    # -----------------------------------------------------
    # Immich Machine Learning (GPU)
    # -----------------------------------------------------
    - name: immich-machine-learning
      image: ghcr.io/immich-app/immich-machine-learning:release-cuda
      annotations:
        io.kubernetes.cri-o.Devices: '["0"]'
      env:
        - name: MACHINE_LEARNING_HOST
          value: "0.0.0.0"
        - name: MACHINE_LEARNING_PORT
          value: "3003"
        - name: MACHINE_LEARNING_WORKERS
          value: "1"
        - name: MACHINE_LEARNING_WORKER_TIMEOUT
          value: "120"
      ports:
        - containerPort: 3003
      volumeMounts:
        - name: ml-cache
          mountPath: /cache
      restartPolicy: Always

  # -------------------------------------------------------
  # Volumes
  # -------------------------------------------------------
  volumes:

    # Relative paths (config/state/cache)
    - name: postgres-data
      hostPath:
        path: ./postgres-data
        type: DirectoryOrCreate

    - name: redis-data
      hostPath:
        path: ./redis-data
        type: DirectoryOrCreate

    - name: postgres-initdb
      hostPath:
        path: ./postgres-initdb
        type: DirectoryOrCreate

    - name: ml-cache
      hostPath:
        path: ./model-cache
        type: DirectoryOrCreate

    # Absolute paths (actual media/content)
    - name: immich-uploads
      hostPath:
        path: /mnt/storage/immich/uploads
        type: Directory

    - name: immich-thumbs
      hostPath:
        path: /mnt/storage/immich/thumbs
        type: Directory

    - name: photo-archive
      hostPath:
        path: /mnt/storage/photo_archive
        type: Directory

