# Media Services
# - Plex
# - Jellyfin

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - ${VOLUME_PATH}/plex-config:/config
      - ${VOLUME_PATH}/transcode:/transcode
      - ${MEDIA_PATH}/movies:/data/movies:ro
      - ${MEDIA_PATH}/demos:/data/demos:ro
      - ${MEDIA_PATH}/photos:/data/photos:ro
      - ${MEDIA_PATH}/tv-shows:/data/tv-shows:ro
    ports:
      - "32400:32400"
    networks:
      - media-network

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOLUME_PATH}/jellyfin-config:/config
      - ${VOLUME_PATH}/transcode:/transcode
      - ${MEDIA_PATH}/movies:/data/movies:ro
      - ${MEDIA_PATH}/demos:/data/demos:ro
      - ${MEDIA_PATH}/photos:/data/photos:ro
      - ${MEDIA_PATH}/tv-shows:/data/tv-shows:ro
    ports:
      - "8096:8096"
    networks:
      - media-network

networks:
  media-network:
    external: true
