# Media Services - Podman Version
# - Plex
# - Jellyfin
# - Podman Auto-Update (systemd-based)
#
# Usage: podman compose up -d --force-recreate --remove-orphans

name: media-stack

networks:
  media-network:
    external: true
  observability-network:
    external: true

# Named volumes for persistent data
volumes:
  plex-config:
    driver: local
  jellyfin-config:
    driver: local
  transcode:
    driver: local

services:
  ## -------------------------
  ## Plex (Media Server)
  ## -------------------------
  plex:
    image: linuxserver/plex:latest
    container_name: media-plex
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex-config:/config
      - transcode:/transcode
      - ${MEDIA_PATH}/movies:/data/movies:ro
      - ${MEDIA_PATH}/demos:/data/demos:ro
      - ${MEDIA_PATH}/tv-shows:/data/tv-shows:ro
    ports:
      - ${PLEX_PORT:-32400}:32400
    networks:
      - media-network
      - observability-network
    labels:
      # Enable Podman auto-update
      - "io.containers.autoupdate=registry"
    # GPU access for Podman
    # Option 1: Using CDI (requires nvidia-container-toolkit)
    # devices:
    #   - nvidia.com/gpu=all
    
    # Option 2: Direct device mapping (works without CDI)
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    security_opt:
      - label=disable

  ## -------------------------
  ## Jellyfin (Media Server)
  ## -------------------------
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: media-jellyfin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - jellyfin-config:/config
      - transcode:/transcode
      - ${MEDIA_PATH}/movies:/data/movies:ro
      - ${MEDIA_PATH}/demos:/data/demos:ro
      - ${MEDIA_PATH}/photos:/data/photos:ro
      - ${MEDIA_PATH}/tv-shows:/data/tv-shows:ro
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
    networks:
      - media-network
      - observability-network
    labels:
      # Enable Podman auto-update
      - "io.containers.autoupdate=registry"
    # GPU access for Podman
    # Option 1: Using CDI (requires nvidia-container-toolkit)
    # devices:
    #   - nvidia.com/gpu=all
    
    # Option 2: Direct device mapping (works without CDI)
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    security_opt:
      - label=disable
