# Usage:
#   podman kube play wyoming-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: wyoming-pod
spec:
  containers:
    - name: wyoming-whisper
      image: rhasspy/wyoming-whisper
      args: ["--model", "tiny-int8", "--language", "en"]
      volumeMounts:
        - name: whisper-data
          mountPath: /data
      ports:
        - containerPort: 10300
          hostPort: 10300
      restartPolicy: Always
      resources:
        limits:
          nvidia.com/gpu: "1"

    - name: wyoming-piper
      image: rhasspy/wyoming-piper
      args: ["--voice", "en_US-lessac-medium"]
      volumeMounts:
        - name: piper-data
          mountPath: /data
      ports:
        - containerPort: 10200
          hostPort: 10200
      restartPolicy: Always
      resources:
        limits:
          nvidia.com/gpu: "1"

  volumes:
    - name: whisper-data
      hostPath:
        path: ./whisper-data
        type: DirectoryOrCreate

    - name: piper-data
      hostPath:
        path: ./piper-data
        type: DirectoryOrCreate
