# Proxy Stack
# - Caddy
#
# Usage: docker compose up -d --force-recreate --remove-orphans --pull always

name: proxy-stack

networks:
  proxy-network:
    external: true

volumes:
  caddy-data:
  caddy-config:

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy-caddy
    restart: always
    environment:
      LOCAL_DOMAIN: ${LOCAL_DOMAIN:-localhost}
      CLOUDFLARE_EMAIL: ${CF_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      ACME_AGREE: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:2019:2019"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - proxy-network
