# AI and Search Services
# - Ollama
# - Open WebUI
# - SearXNG

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - OLLAMA_KEEP_ALIVE=15m
      - ENABLE_IMAGE_GENERATION=True
    # If you would like to use external storage
    #volumes:
    #  - /mnt/e/ai-services/ollama:/root/.ollama
    networks:
      - ai-network
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    depends_on:
      - ollama
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - ENABLE_RAG_WEBSEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=10
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=50
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    # If you would like to use external storage
    #volumes:
    #  - /mnt/e/ai-services/open-webui:/app/backend/data
    networks:
      - ai-network
    ports:
      - "8000:8080"
    extra_hosts:
      - host.docker.internal:host-gateway

  searxng:
    depends_on:
      - ollama
      - open-webui
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    # If you would like to use external storage
    #volumes:
    #  - /mnt/e/ai-services/searxng:/etc/searxng
    networks:
      - ai-network
    ports:
      - "8888:8080"

networks:
  ai-network:
    external: true
