# Core stack Kubernetes manifest - core-stack namespace
# Contains: cloudflared (Cloudflare tunnel)
#
# Usage: play kube --configmap core-stack-env.yaml core-stack.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: core-stack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: core-stack
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: docker.io/cloudflare/cloudflared:latest
          args: ["tunnel", "run"]
          envFrom:
            - configMapRef:
                name: core-stack-env
          # If you later prefer secrets, replace envFrom with secretRef
          resources: {}
---
