# Core Stack
# - Portainer
# - Cloudflare Tunnel
# - Watchtower
#
# Usage: docker compose up -d --force-recreate --remove-orphans --pull always

name: core-stack

networks:
  core-network:
    external: true
  # Connect to Observability
  # observability-network:
  #   external: true

volumes:
  portainer-data:

services:
  ## -------------------------
  ## Portainer (UI for Docker)
  ## -------------------------
  portainer:
    image: portainer/portainer-ce:latest
    container_name: core-portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    networks:
      - core-network
    #  - observability-network
    ports:
      - ${PORTAINER_PORT:-9443}:9443
    labels:
      - "com.centurylinklabs.watchtower.scope=core"

  ## -------------------------
  ## cloudflared (Cloudflare Tunnel)
  ## -------------------------
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: core-cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - core-network
    #  - observability-network
    labels:
      - "com.centurylinklabs.watchtower.scope=core"

  ## -------------------------
  ## Watchtower (Auto-updates)
  ## -------------------------
  watchtower:
    image: containrrr/watchtower:latest
    container_name: core-watchtower
    restart: always
    command: >
      --scope ai
      --cleanup
      --schedule "0 0 3 * * 1" # every Monday 03:00
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core-network
