# Core Stack - Podman Version
# - Portainer
# - Cloudflare Tunnel
# - Podman Auto-Update (systemd-based)
#
# Usage: podman-compose pull && podman-compose up -d --force-recreate --remove-orphans

name: core-stack

networks:
  core-network:
    external: true
  observability-network:
    external: true

# Named volumes for persistent data
volumes:
  portainer-data:
    driver: local

services:
  ## -------------------------
  ## Portainer (UI for Podman)
  ## -------------------------
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: core-portainer
    restart: always
    volumes:
      # Podman socket binding - needs proper permissions
      - /run/user/${PUID}/podman/podman.sock:/var/run/docker.sock:ro
      # Named volume for persistent data
      - portainer-data:/data
    networks:
      - core-network
      - observability-network
    ports:
      - ${PORTAINER_PORT:-9443}:9443
    labels:
      # Enable Podman auto-update
      - "io.containers.autoupdate=registry"
    security_opt:
      - label=disable

  ## -------------------------
  ## cloudflared (Cloudflare Tunnel)
  ## -------------------------
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: core-cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - core-network
      - observability-network
    labels:
      # Enable Podman auto-update
      - "io.containers.autoupdate=registry"