# Productivity Services
# - NextCloud

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    # If you would like to use external storage
    #volumes:
    #  - /mnt/e/productivity-services/nextcloud-data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - productivity-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          cpus: '1.0'
          memory: 1.5G

networks:
  productivity-network:
    external: true
